# Generated by Django 4.1.5 on 2023-02-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_price_menu_priceofitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='priceofitem',
            new_name='price',
        ),
    ]
