# Generated by Django 4.1.5 on 2023-02-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_priceofitem_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='item_id',
            field=models.IntegerField(default=1),
        ),
    ]
