# Generated by Django 4.1.5 on 2023-02-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_menu_available_remove_menu_cuisine_and_more'),
    ]

    operations = [
    ]
