# Generated by Django 4.1.5 on 2023-02-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20230201_2007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drinks',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
