# Generated by Django 4.1.5 on 2023-02-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_drinkscategory_drinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reservation_day', models.CharField(max_length=100)),
                ('seats', models.IntegerField()),
            ],
        ),
    ]
