# Generated by Django 4.1.5 on 2023-02-10 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_employees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logger',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='menu_itm',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category_id',
        ),
    ]
